name: "[CD] Continuous Delivery"

# on:
#   push:
#     branches: [main]
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      ## Common ci steps
      - uses: actions/checkout@v3
      # ===============================
      - name: "Debug"
        run: "ls -la"
      - name: "Install Dependencies"
        run: "npm install"
      - name: "Publish to Vercel"
        run: "npx vercel --prod"
