name: "[CI] Continuous Integration"

#Sempre que houver um commit ou um PR for aberto
on:
    pull_request:
        types: [opened, synchronize]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            ## Common ci steps
            - uses: actions/checkout@v3
            # ===============================
            - name: "Debug"
              run: "ls -la"
            - name: "Lint"
              run: "yarn lint"
