name: "[CI] Continuous Integration"

#Sempre que houver um commit ou um PR for aberto
on:
    pull_request:
        types: [opened, synchronize]

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            ## Common ci steps
            - uses: actions/checkout@v3
            # ===============================
            - name: "Debug"
              run: "ls -la"
            - name: "Install Dependencies"
              run: "yarn"
            - name: "Lint"
              run: "yarn lint"
    test:
        runs-on: ubuntu-latest
        container: cypress/browsers:node18.12.0-chrome107
        steps:
            ## Common ci steps
            - uses: actions/checkout@v3
            # ===============================
            - name: "Install Dependencies"
              run: "yarn"
            - name: "Test"
              run: "yarn test"
